apiVersion: batch/v1beta1
kind: CronJob
metadata:
   name: test-job2
spec:
   schedule: "*/2 * * * *" 
   concurrencyPolicy: Forbid
   successfulJobsHistoryLimit: 5
   failedJobsHistoryLimit: 5
   jobTemplate:
     spec:
       template:
         spec:
           containers:
           - name: whalesay
             image: docker/whalesay
             command : ["cowsay", "This is Kubernetes test job 2"]
           restartPolicy: OnFailure 
